### ISSUE TITLE
Please port qjackspa to Qt5

### ISSUE THREAD

**Issue by sten0** [7890/ng-jackspa#1]
Hi!

Thank you for maintaining ng-jackspa :-)  I've noticed Debian (and derivatives such as Ubuntu) do not yet have a simple jack ladspa host, so I'd like to package this software.  Unfortunately the Qt4 dependency is a blocker, because we're in the process of removing Qt4.  Would you please port qjackspa to Qt5?

Sincerely,
Nicholas

**Comment by 7890** [comment]
Hi, this repository is a copy from https://repo.or.cz/ng-jackspa.git/
It's an archive copy of V1.0 from 2013, there are no plans on my side to change or maintain ng-ladspa. So unfortunately the answer is no.
Out of interest, have you tried what happens when compiling the existing source for Qt5? Maybe it's not much to change however that's pure speculation.

**Comment by sten0** [comment]
Hi,

CCing ng-jackspa maintainer

7890 <notifications@github.com> writes:

> Hi, this repository is a copy from https://repo.or.cz/ng-jackspa.git/
> It's an archive copy of V1.0 from 2013, there are no plans on my side
> to change or maintain ng-ladspa. So unfortunately the answer is no.
> Out of interest, have you tried what happens when compiling the
> existing source for Qt5? Maybe it's not much to change however that's
> pure speculation.

Oh, I was hoping it was a mirror in the sense that kernel.org also has a
github project mirror...

You're right, it shouldn't be hard to adapt to Qt5, but if I fixed it up
ng-jackspa to work with Qt5 then I'd become the defacto maintainer of
the project, or arguably of the fork...sadly I can't commit to this at
this time.

G.raud, would you please comment?  This is a nice piece of software that
I'd like to package for Debian.

Regards,
Nicholas

**Comment by 7890** [comment]
@sten0, OK thanks for the hints. I've added a comment to the repository title, sorry about the confusion.

**Comment by 7890** [comment]
I will disable the 'issues' function, since they should go to the originating repository.
